export interface Product {
  id: string;
  name: string;
  subtitle: string;
  category: string;
  rating: number;
  reviewCount: number;
  currentPrice: number;
  mrp: number;
  discount: number;
  images: string[];
  description: string;
  specifications: Array<{ label: string; value: string }>;
  highlights: string[];
  variants?: {
    colors?: Array<{ id: string; label: string }>;
    sizes?: Array<{ id: string; label: string }>;
    types?: Array<{ id: string; label: string }>;
    packs?: Array<{ id: string; label: string }>;
  };
}

export const allProducts: Product[] = [
  // COLOR SHEETS & PAPER
  {
    id: 'a3-color-sheets',
    name: 'A3 Color Sheets',
    subtitle: 'Pack of 20 · Assorted colors · Premium quality',
    category: 'Paper & Sheets',
    rating: 4.5,
    reviewCount: 856,
    currentPrice: 120,
    mrp: 180,
    discount: 33,
    images: ['https://images.unsplash.com/photo-1669286211114-9f17251fd0e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xvcmVkJTIwcGFwZXIlMjBzaGVldHMlMjBwYWNrfGVufDF8fHx8MTc2OTgzOTIxNXww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium quality A3 colored paper sheets perfect for large format projects, presentations, and creative artwork. Vibrant assorted colors.',
    specifications: [
      { label: 'Size', value: 'A3 (297 x 420 mm)' },
      { label: 'Colors', value: 'Mix - Assorted' },
      { label: 'Finish', value: 'White matte' },
      { label: 'Quantity', value: '20 sheets' },
      { label: 'Weight', value: '80 GSM' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '20 sheets per pack',
      'Large A3 format',
      'Vibrant assorted colors',
      'Perfect for art projects',
    ],
  },
  {
    id: 'a4-color-sheets',
    name: 'A4 Color Paper Sheets',
    subtitle: 'Pack of 20 · Assorted colors · Standard size',
    category: 'Paper & Sheets',
    rating: 4.4,
    reviewCount: 987,
    currentPrice: 80,
    mrp: 120,
    discount: 33,
    images: ['https://images.unsplash.com/photo-1669286211114-9f17251fd0e3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xvcmVkJTIwcGFwZXIlMjBzaGVldHMlMjBwYWNrfGVufDF8fHx8MTc2OTgzOTIxNXww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Standard A4 colored paper sheets ideal for crafts, school projects, and presentations. Available in vibrant assorted colors.',
    specifications: [
      { label: 'Size', value: 'A4 (210 x 297 mm)' },
      { label: 'Colors', value: 'Mix - Assorted' },
      { label: 'Finish', value: 'White matte' },
      { label: 'Quantity', value: '20 sheets' },
      { label: 'Weight', value: '80 GSM' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '20 sheets per pack',
      'Standard A4 size',
      'Multiple bright colors',
      'Ideal for crafts and projects',
    ],
  },
  {
    id: 'brown-paper-laminated',
    name: 'Brown Kraft Paper - Laminated',
    subtitle: 'Black color · Durable lamination · Quality material',
    category: 'Paper & Sheets',
    rating: 4.3,
    reviewCount: 423,
    currentPrice: 45,
    mrp: 65,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1763030861291-b7e65ae261c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxicm93biUyMGtyYWZ0JTIwcGFwZXIlMjBsYW1pbmF0ZWR8ZW58MXx8fHwxNzY5ODM5MjE2fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Durable laminated brown kraft paper in black color. Perfect for book covers, project work, and protective wrapping.',
    specifications: [
      { label: 'Type', value: 'Laminated brown paper' },
      { label: 'Size', value: 'N/A' },
      { label: 'Color', value: 'Black' },
      { label: 'Finish', value: 'Black laminated' },
      { label: 'Quantity', value: '1 sheet' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Laminated for durability',
      'Black color finish',
      'Perfect for book covers',
      'Water-resistant coating',
    ],
  },
  {
    id: 'packing-paper-brown',
    name: 'Brown Packing Paper',
    subtitle: 'Pack of 25 · Mix sizes · Wrapping material',
    category: 'Paper & Sheets',
    rating: 4.2,
    reviewCount: 534,
    currentPrice: 95,
    mrp: 140,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1625415259768-f10363da46be?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWNraW5nJTIwcGFwZXIlMjBicm93biUyMHdyYXBwaW5nfGVufDF8fHx8MTc2OTgzOTIzNHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Bulk pack of brown packing paper for wrapping, shipping, and storage needs. Eco-friendly kraft paper.',
    specifications: [
      { label: 'Type', value: 'Packing paper' },
      { label: 'Size', value: 'Mix sizes' },
      { label: 'Color', value: 'Mix brown shades' },
      { label: 'Quantity', value: '25 sheets' },
      { label: 'Material', value: 'Kraft paper' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '25 sheets per pack',
      'Eco-friendly kraft paper',
      'Versatile packing material',
      'Multiple size options',
    ],
  },
  {
    id: 'paper-easy-70gsm',
    name: 'JK Easy A4 Paper - 70 GSM',
    subtitle: 'Premium white · 70 GSM · Printer paper',
    category: 'Paper & Sheets',
    rating: 4.6,
    reviewCount: 2145,
    currentPrice: 245,
    mrp: 320,
    discount: 23,
    images: ['https://images.unsplash.com/photo-1665512751717-219c5687cb6e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMHByaW50ZXIlMjBwYXBlciUyMEE0fGVufDF8fHx8MTc2OTgzOTIzNHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium quality JK Easy copier paper ideal for everyday printing and copying needs. Smooth white finish.',
    specifications: [
      { label: 'Brand', value: 'JK' },
      { label: 'Type', value: 'Easy 70 GSM' },
      { label: 'Size', value: 'A4' },
      { label: 'Color', value: 'White' },
      { label: 'Weight', value: '70 GSM' },
      { label: 'Sheets', value: '500 per pack' },
    ],
    highlights: [
      '70 GSM quality paper',
      'Smooth printing surface',
      'Compatible with all printers',
      'Premium JK brand',
    ],
  },
  {
    id: 'paper-copier-75gsm',
    name: 'JK Copier A4 Paper - 75 GSM',
    subtitle: 'Premium white · 75 GSM · High quality',
    category: 'Paper & Sheets',
    rating: 4.7,
    reviewCount: 1876,
    currentPrice: 265,
    mrp: 350,
    discount: 24,
    images: ['https://images.unsplash.com/photo-1665512751717-219c5687cb6e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMHByaW50ZXIlMjBwYXBlciUyMEE0fGVufDF8fHx8MTc2OTgzOTIzNHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'High-quality JK copier paper with 75 GSM thickness for professional printing and copying.',
    specifications: [
      { label: 'Brand', value: 'JK' },
      { label: 'Type', value: 'Copier 75 GSM' },
      { label: 'Size', value: 'A4' },
      { label: 'Color', value: 'White' },
      { label: 'Weight', value: '75 GSM' },
      { label: 'Sheets', value: '500 per pack' },
    ],
    highlights: [
      'Premium 75 GSM thickness',
      'Professional quality',
      'Jam-free printing',
      'Trusted JK brand',
    ],
  },
  {
    id: 'paper-letter-pad',
    name: 'Indo Paper Letter Pad',
    subtitle: 'Big size · Quality writing paper',
    category: 'Paper & Sheets',
    rating: 4.3,
    reviewCount: 645,
    currentPrice: 55,
    mrp: 80,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1642774674065-848b55d4c5c6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYXBlciUyMGxldHRlciUyMHBhZCUyMHdyaXRpbmd8ZW58MXx8fHwxNzY5ODM5MjMzfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Quality letter writing pad with smooth paper. Perfect for formal and personal correspondence.',
    specifications: [
      { label: 'Brand', value: 'Indo' },
      { label: 'Type', value: 'Letter pad' },
      { label: 'Size', value: 'Big' },
      { label: 'Color', value: 'Mix colors' },
      { label: 'Pages', value: '100 sheets' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Large format letter pad',
      'Smooth writing surface',
      'Quality paper',
      '100 sheets per pad',
    ],
  },

  // CALCULATORS & ELECTRONICS
  {
    id: 'calculator-casio',
    name: 'Casio MJ-12D Calculator',
    subtitle: 'Desktop calculator · 12-digit display',
    category: 'Calculators',
    rating: 4.7,
    reviewCount: 1523,
    currentPrice: 599,
    mrp: 899,
    discount: 33,
    images: ['https://images.unsplash.com/photo-1611532736579-6b16e2b50449?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXNpbyUyMGNhbGN1bGF0b3J8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional desktop calculator with large 12-digit display and durable keys. Ideal for office, home, and school use.',
    specifications: [
      { label: 'Model', value: 'MJ-12D' },
      { label: 'Display', value: '12-digit LCD' },
      { label: 'Color', value: 'Black' },
      { label: 'Power', value: 'Dual power (Solar + Battery)' },
      { label: 'Brand', value: 'Casio' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Large 12-digit display',
      'Dual power: Solar and battery',
      'Tax and memory functions',
      'Durable plastic keys',
    ],
  },
  {
    id: 'battery-panasonic-aaa',
    name: 'Panasonic AAA Battery Cells - Gold',
    subtitle: 'Long-lasting power · Pack of 1 · Premium quality',
    category: 'Electronics',
    rating: 4.8,
    reviewCount: 3214,
    currentPrice: 35,
    mrp: 50,
    discount: 30,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXR0ZXJ5JTIwY2VsbCUyMGFhYXxlbnwxfHx8fDE3MzgzNDk0Mzh8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium quality AAA batteries from Panasonic. Long-lasting power for all your devices.',
    specifications: [
      { label: 'Type', value: 'AAA Alkaline' },
      { label: 'Voltage', value: '1.5V' },
      { label: 'Color', value: 'Gold' },
      { label: 'Quantity', value: '1 cell' },
      { label: 'Brand', value: 'Panasonic' },
      { label: 'Shelf Life', value: '10 years' },
    ],
    highlights: [
      'Long-lasting power',
      'Premium Panasonic quality',
      '10-year shelf life',
      'Suitable for all devices',
    ],
  },
  {
    id: 'battery-panasonic-aa',
    name: 'Panasonic AA Battery Cells - Gold',
    subtitle: 'Long-lasting power · Pack of 1 · Premium quality',
    category: 'Electronics',
    rating: 4.8,
    reviewCount: 2987,
    currentPrice: 40,
    mrp: 60,
    discount: 33,
    images: ['https://images.unsplash.com/photo-1583863788434-e58a36330cf0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYXR0ZXJ5JTIwY2VsbCUyMGFhYXxlbnwxfHx8fDE3MzgzNDk0Mzh8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'High-capacity AA batteries from Panasonic. Reliable power for high-drain devices.',
    specifications: [
      { label: 'Type', value: 'AA Alkaline' },
      { label: 'Voltage', value: '1.5V' },
      { label: 'Color', value: 'Gold' },
      { label: 'Quantity', value: '1 cell' },
      { label: 'Brand', value: 'Panasonic' },
      { label: 'Shelf Life', value: '10 years' },
    ],
    highlights: [
      'High-capacity AA size',
      'Reliable power',
      'Premium quality',
      'Long shelf life',
    ],
  },

  // NOTEBOOKS & BOOKS
  {
    id: 'coloring-book',
    name: 'Creative Coloring Book',
    subtitle: 'Fun designs · Thick pages · For kids',
    category: 'Books',
    rating: 4.7,
    reviewCount: 2341,
    currentPrice: 95,
    mrp: 150,
    discount: 37,
    images: ['https://images.unsplash.com/photo-1649750291589-8812197b698c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb2xvcmluZyUyMGJvb2slMjBjaGlsZHJlbnxlbnwxfHx8fDE3Njk4MzkyMTZ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Engaging coloring book with fun and creative designs for children. Features thick pages that prevent color bleed-through.',
    specifications: [
      { label: 'Pages', value: '40 designs' },
      { label: 'Paper Quality', value: 'Thick, bleed-proof' },
      { label: 'Size', value: 'A4' },
      { label: 'Age Group', value: '3-10 years' },
      { label: 'Binding', value: 'Spiral' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '40 fun designs',
      'Thick, quality paper',
      'No color bleed-through',
      'Perfect for creative kids',
    ],
  },
  {
    id: 'copy-single-line',
    name: 'Classmate Single Line Copy',
    subtitle: '120 pages · Ruled · Premium quality',
    category: 'Notebooks',
    rating: 4.5,
    reviewCount: 3421,
    currentPrice: 40,
    mrp: 60,
    discount: 33,
    images: ['https://images.unsplash.com/photo-1517842645767-c639042777db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxub3RlYm9vayUyMHN0YXRpb25lcnl8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium quality ruled notebook with 120 pages. Perfect for school, college, and office use.',
    specifications: [
      { label: 'Type', value: 'Single Line / Ruled' },
      { label: 'Pages', value: '120' },
      { label: 'Paper Quality', value: 'Mix - Premium white' },
      { label: 'Size', value: 'Regular' },
      { label: 'Brand', value: 'Classmate' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '120 pages of quality paper',
      'Smooth writing surface',
      'Durable cover',
      'Perfect for daily use',
    ],
  },
  {
    id: 'copy-math',
    name: 'Classmate Math Copy',
    subtitle: '120 pages · Square ruled · Math practice',
    category: 'Notebooks',
    rating: 4.5,
    reviewCount: 2876,
    currentPrice: 42,
    mrp: 65,
    discount: 35,
    images: ['https://images.unsplash.com/photo-1517842645767-c639042777db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxub3RlYm9vayUyMHN0YXRpb25lcnl8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Square ruled notebook designed for mathematics practice. 120 pages of quality paper.',
    specifications: [
      { label: 'Type', value: 'Math / Square ruled' },
      { label: 'Pages', value: '120' },
      { label: 'Paper Quality', value: 'Mix - Premium' },
      { label: 'Size', value: 'Regular' },
      { label: 'Brand', value: 'Classmate' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Square grid for math',
      '120 quality pages',
      'Ideal for calculations',
      'Student-friendly design',
    ],
  },
  {
    id: 'copy-english',
    name: 'Classmate English Copy',
    subtitle: '120 pages · 4-line ruled · English writing',
    category: 'Notebooks',
    rating: 4.4,
    reviewCount: 2543,
    currentPrice: 40,
    mrp: 60,
    discount: 33,
    images: ['https://images.unsplash.com/photo-1517842645767-c639042777db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxub3RlYm9vayUyMHN0YXRpb25lcnl8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Four-line ruled notebook perfect for English handwriting practice. 120 pages of premium paper.',
    specifications: [
      { label: 'Type', value: 'English / 4-line ruled' },
      { label: 'Pages', value: '120' },
      { label: 'Paper Quality', value: 'Mix - Premium' },
      { label: 'Size', value: 'Regular' },
      { label: 'Brand', value: 'Classmate' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '4-line ruling for handwriting',
      '120 pages',
      'Perfect for English practice',
      'Quality Classmate brand',
    ],
  },
  {
    id: 'drawing-book-ajanta',
    name: 'Ajanta Drawing Book',
    subtitle: 'Blank pages · Thick paper · Artist quality',
    category: 'Books',
    rating: 4.5,
    reviewCount: 1234,
    currentPrice: 75,
    mrp: 110,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1506880018603-83d5b814b5a6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkcmF3aW5nJTIwYm9vayUyMHBhcGVyfGVufDF8fHx8MTczODM0OTQzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'High-quality drawing book with thick paper suitable for pencils, crayons, and light markers.',
    specifications: [
      { label: 'Brand', value: 'Ajanta' },
      { label: 'Pages', value: '50 sheets' },
      { label: 'Paper Weight', value: '120 GSM' },
      { label: 'Size', value: 'A4' },
      { label: 'Binding', value: 'Spiral' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Thick 120 GSM paper',
      'Smooth drawing surface',
      'Spiral binding',
      'Professional quality',
    ],
  },
  {
    id: 'exam-board',
    name: 'Exam Writing Board',
    subtitle: 'Clipboard style · Smooth surface · Student essential',
    category: 'Stationery Accessories',
    rating: 4.6,
    reviewCount: 1567,
    currentPrice: 85,
    mrp: 130,
    discount: 35,
    images: ['https://images.unsplash.com/photo-1614492898637-435e0f87cef8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxleGFtJTIwd3JpdGluZyUyMGJvYXJkJTIwY2xpcGJvYXJkfGVufDF8fHx8MTc2OTgzOTIxNnww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Sturdy exam writing board with smooth surface and strong clip. Essential for students during examinations.',
    specifications: [
      { label: 'Type', value: 'Exam board / Clipboard' },
      { label: 'Material', value: 'Plastic/Wood composite' },
      { label: 'Size', value: 'A4' },
      { label: 'Clip Type', value: 'Metal spring clip' },
      { label: 'Surface', value: 'Smooth writing surface' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Smooth writing surface',
      'Strong clip mechanism',
      'Lightweight and portable',
      'Perfect for exams',
    ],
  },
  {
    id: 'long-copy-classmate',
    name: 'Classmate Long Copy - 172 Pages',
    subtitle: '172 pages · Extra pages · Value pack',
    category: 'Notebooks',
    rating: 4.6,
    reviewCount: 1789,
    currentPrice: 65,
    mrp: 95,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1517842645767-c639042777db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxub3RlYm9vayUyMHN0YXRpb25lcnl8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Extra-long notebook with 172 pages for extended use. Perfect for semester-long notes.',
    specifications: [
      { label: 'Type', value: 'Long copy / Ruled' },
      { label: 'Pages', value: '172' },
      { label: 'Paper Quality', value: 'Premium white' },
      { label: 'Size', value: 'Regular' },
      { label: 'Brand', value: 'Classmate' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '172 pages - Extra long',
      'Value for money',
      'Quality paper',
      'Perfect for long-term use',
    ],
  },
  {
    id: 'notebook-spiral-a4',
    name: 'Spiral Notebook A4',
    subtitle: 'Quality paper · Spiral bound · Multipurpose',
    category: 'Notebooks',
    rating: 4.4,
    reviewCount: 1432,
    currentPrice: 95,
    mrp: 140,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1630448925000-f014372affc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGlyYWwlMjBub3RlYm9vayUyMHJ1bGVkJTIwcGFnZXN8ZW58MXx8fHwxNzY5ODM5MjE4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'A4 spiral notebook with quality paper. Ideal for notes, sketches, and everyday writing.',
    specifications: [
      { label: 'Type', value: 'Spiral bound' },
      { label: 'Size', value: 'A4' },
      { label: 'Pages', value: '100 sheets' },
      { label: 'Paper Quality', value: 'Premium' },
      { label: 'Binding', value: 'Wire spiral' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'A4 size format',
      'Spiral bound for easy use',
      '100 quality sheets',
      'Versatile notebook',
    ],
  },
  {
    id: 'register-172-pages',
    name: 'Classmate Register - 172 Pages',
    subtitle: 'A4 size · Hardbound · Professional',
    category: 'Notebooks',
    rating: 4.5,
    reviewCount: 987,
    currentPrice: 125,
    mrp: 180,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1517842645767-c639042777db?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxub3RlYm9vayUyMHN0YXRpb25lcnl8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional hardbound register with 172 pages. Ideal for record-keeping and formal documentation.',
    specifications: [
      { label: 'Type', value: 'Register / Hardbound' },
      { label: 'Pages', value: '172' },
      { label: 'Size', value: 'A4' },
      { label: 'Cover', value: 'Hardcover' },
      { label: 'Brand', value: 'Classmate' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Professional register',
      'Hardbound durability',
      '172 quality pages',
      'A4 format',
    ],
  },
  {
    id: 'writing-book-spiral-67',
    name: 'Neelgagan Writing Book - No 67',
    subtitle: 'Spiral bound · Quality pages · Student notebook',
    category: 'Notebooks',
    rating: 4.3,
    reviewCount: 876,
    currentPrice: 75,
    mrp: 110,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1630448925000-f014372affc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGlyYWwlMjBub3RlYm9vayUyMHJ1bGVkJTIwcGFnZXN8ZW58MXx8fHwxNzY5ODM5MjE4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Spiral-bound writing book from Neelgagan. Perfect for students and daily note-taking.',
    specifications: [
      { label: 'Model', value: 'Spiral - No 67' },
      { label: 'Type', value: 'Writing book' },
      { label: 'Size', value: 'Regular' },
      { label: 'Pages', value: 'Mix pages' },
      { label: 'Brand', value: 'Neelgagan' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Spiral binding',
      'Quality pages',
      'Student-friendly',
      'Durable construction',
    ],
  },
  {
    id: 'writing-pad-conference',
    name: 'Conference Writing Pad',
    subtitle: 'Professional pad · Quality paper · Office use',
    category: 'Notebooks',
    rating: 4.5,
    reviewCount: 654,
    currentPrice: 110,
    mrp: 160,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1630448925000-f014372affc7?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzcGlyYWwlMjBub3RlYm9vayUyMHJ1bGVkJTIwcGFnZXN8ZW58MXx8fHwxNzY5ODM5MjE4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional conference writing pad with premium paper for meeting notes and professional use.',
    specifications: [
      { label: 'Type', value: 'Conference pad' },
      { label: 'Size', value: 'Large' },
      { label: 'Pages', value: 'Mix pages' },
      { label: 'Paper Quality', value: 'Premium' },
      { label: 'Brand', value: 'Neelgagan' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Professional design',
      'Premium paper quality',
      'Ideal for meetings',
      'Large format',
    ],
  },
  {
    id: 'sticky-notepad',
    name: 'Dochaan Sticky Notepad - 3x3',
    subtitle: 'Self-adhesive · 3x3 inches · Removable notes',
    category: 'Notebooks',
    rating: 4.6,
    reviewCount: 1234,
    currentPrice: 55,
    mrp: 85,
    discount: 35,
    images: ['https://images.unsplash.com/photo-1762318897823-f7bc4df5b1e6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzdGlja3klMjBub3RlcyUyMHBhZCUyMHllbGxvd3xlbnwxfHx8fDE3Njk4MzkyMjN8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Convenient sticky notepad with self-adhesive backing. Perfect for reminders and quick notes.',
    specifications: [
      { label: 'Type', value: 'Sticky notepad' },
      { label: 'Size', value: '3x3 inches' },
      { label: 'Adhesive', value: 'Repositionable' },
      { label: 'Sheets', value: '100 per pad' },
      { label: 'Brand', value: 'Dochaan' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Self-adhesive notes',
      '3x3 inch size',
      'Repositionable',
      '100 sheets per pad',
    ],
  },

  // CORRECTION SUPPLIES
  {
    id: 'correction-pen-infinity',
    name: 'Infinity Correction Pen',
    subtitle: 'Quick dry · 7 ml · Smooth application',
    category: 'Correction Supplies',
    rating: 4.2,
    reviewCount: 892,
    currentPrice: 25,
    mrp: 40,
    discount: 38,
    images: ['https://images.unsplash.com/photo-1586281380349-632531db7ed4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3JyZWN0aW9uJTIwcGVuJTIwd2hpdGV8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Fast-drying correction pen for quick and clean corrections. Fine tip allows for precise application.',
    specifications: [
      { label: 'Type', value: 'Correction pen' },
      { label: 'Volume', value: '7 Ml' },
      { label: 'Color', value: 'Mix white shades' },
      { label: 'Tip Type', value: 'Fine point' },
      { label: 'Brand', value: 'Infinity' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Quick-drying formula',
      'Precise fine tip',
      'Covers all ink types',
      '7ml capacity',
    ],
  },
  {
    id: 'correction-tape-wonder',
    name: 'Wonder Correction Tape',
    subtitle: 'Instant correction · Tear-resistant · Easy use',
    category: 'Correction Supplies',
    rating: 4.5,
    reviewCount: 1123,
    currentPrice: 45,
    mrp: 65,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1612815154075-baa83e1c499f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3JyZWN0aW9uJTIwdGFwZSUyMHdoaXRlfGVufDF8fHx8MTczODM0OTQzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Convenient correction tape for instant corrections. Tear-resistant tape applies smoothly.',
    specifications: [
      { label: 'Type', value: 'Correction tape' },
      { label: 'Length', value: '8 meters' },
      { label: 'Width', value: '5mm' },
      { label: 'Features', value: 'Instant dry, tear-resistant' },
      { label: 'Brand', value: 'Wonder' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Instant correction',
      'Tear-resistant tape',
      'Smooth application',
      'No drying time needed',
    ],
  },
  {
    id: 'double-side-tape',
    name: 'Double Sided Tape',
    subtitle: 'Strong adhesion · Multi-purpose · Easy peel',
    category: 'Tapes & Adhesives',
    rating: 4.4,
    reviewCount: 765,
    currentPrice: 35,
    mrp: 55,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1701442876057-0bcbe9317600?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkb3VibGUlMjBzaWRlZCUyMHRhcGUlMjByb2xsfGVufDF8fHx8MTc2OTgzOTIxN3ww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Strong double-sided adhesive tape for mounting and bonding. Perfect for crafts and displays.',
    specifications: [
      { label: 'Type', value: 'Double sided tape' },
      { label: 'Width', value: '12mm' },
      { label: 'Length', value: '5 meters' },
      { label: 'Adhesive', value: 'Permanent bond' },
      { label: 'Material', value: 'Foam/Paper backing' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Strong adhesion both sides',
      'Multi-purpose use',
      'Clean application',
      'No residue removal',
    ],
  },

  // ADHESIVES & GLUE
  {
    id: 'fevicol-adhesive',
    name: 'Fevicol Adhesive Glue - Small',
    subtitle: 'Small size · All-purpose · Strong bond',
    category: 'Adhesives',
    rating: 4.8,
    reviewCount: 2134,
    currentPrice: 35,
    mrp: 50,
    discount: 30,
    images: ['https://images.unsplash.com/photo-1624969862293-b749659ccc4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnbHVlJTIwYWRoZXNpdmV8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'India\'s most trusted adhesive for paper, cardboard, and craft projects. Creates strong lasting bonds.',
    specifications: [
      { label: 'Type', value: 'Adhesive glue' },
      { label: 'Size', value: 'Small (50g)' },
      { label: 'Color', value: 'White' },
      { label: 'Application', value: 'Paper, cardboard, fabric' },
      { label: 'Brand', value: 'Fevicol' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Strong adhesive bond',
      'Non-toxic and safe',
      'Dries clear',
      'Ideal for crafts',
    ],
  },
  {
    id: 'fevikwik-instant',
    name: 'Fevikwik Instant Adhesive - Pidilite',
    subtitle: 'Instant bonding · 15 pack · Professional use',
    category: 'Adhesives',
    rating: 4.7,
    reviewCount: 1876,
    currentPrice: 85,
    mrp: 120,
    discount: 29,
    images: ['https://images.unsplash.com/photo-1624969862293-b749659ccc4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnbHVlJTIwYWRoZXNpdmV8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Instant super glue for quick repairs and bonding. Professional quality from Pidilite.',
    specifications: [
      { label: 'Type', value: 'Instant adhesive' },
      { label: 'Pack', value: '15 units' },
      { label: 'Application', value: 'Multi-material bonding' },
      { label: 'Setting Time', value: 'Instant (seconds)' },
      { label: 'Brand', value: 'Pidilite' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Instant bonding',
      'Professional quality',
      '15 pack value',
      'Multi-material use',
    ],
  },
  {
    id: 'glue-stick-fevistik',
    name: 'Fevistik Glue Stick - 15gms',
    subtitle: 'No mess · Easy application · 15gms',
    category: 'Adhesives',
    rating: 4.6,
    reviewCount: 1543,
    currentPrice: 28,
    mrp: 40,
    discount: 30,
    images: ['https://images.unsplash.com/photo-1625225233840-695456021cde?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnbHVlJTIwc3RpY2slMjBzdGF0aW9uZXJ5fGVufDF8fHx8MTczODM0OTQzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Clean and convenient glue stick for paper and light cardboard. Non-toxic washable formula.',
    specifications: [
      { label: 'Type', value: 'Stick adhesive' },
      { label: 'Size', value: '15gms' },
      { label: 'Formula', value: 'Non-toxic, washable' },
      { label: 'Application', value: 'Paper, cardboard' },
      { label: 'Brand', value: 'Fevistik' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'No mess application',
      'Non-toxic and safe',
      'Washable formula',
      'Perfect for children',
    ],
  },

  // FILES & FOLDERS
  {
    id: 'file-folder-cobra',
    name: 'RPS Cobra File Folder No 300',
    subtitle: 'A4 size · Flat design · Durable',
    category: 'Files & Folders',
    rating: 4.3,
    reviewCount: 756,
    currentPrice: 65,
    mrp: 90,
    discount: 28,
    images: ['https://images.unsplash.com/photo-1568667256549-094345857637?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmaWxlJTIwZm9sZGVyJTIwb2ZmaWNlfGVufDF8fHx8MTczODM0OTQzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Durable A4 file folder perfect for organizing documents. Features reinforced edges.',
    specifications: [
      { label: 'Model', value: 'No 300 - Flat - Cobra' },
      { label: 'Size', value: 'A4' },
      { label: 'Material', value: 'Premium cardboard' },
      { label: 'Color', value: 'Mix colors' },
      { label: 'Brand', value: 'RPS' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'A4 size standard',
      'Durable construction',
      'Reinforced edges',
      'Multiple color options',
    ],
  },
  {
    id: 'file-display-solo',
    name: 'Solo Display File 10 Pocket',
    subtitle: '10 clear pockets · Document protection · Professional',
    category: 'Files & Folders',
    rating: 4.4,
    reviewCount: 892,
    currentPrice: 85,
    mrp: 120,
    discount: 29,
    images: ['https://images.unsplash.com/photo-1586281380117-5a60ae2050cc?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxkaXNwbGF5JTIwZmlsZSUyMGZvbGRlcnxlbnwxfHx8fDE3MzgzNDk0Mzh8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional display file with 10 clear pockets for document presentation and protection.',
    specifications: [
      { label: 'Type', value: 'Display file' },
      { label: 'Pockets', value: '10 clear pockets' },
      { label: 'Size', value: 'A4' },
      { label: 'Material', value: 'Durable plastic' },
      { label: 'Brand', value: 'Solo' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '10 clear pockets',
      'Professional presentation',
      'Document protection',
      'Durable construction',
    ],
  },
  {
    id: 'file-full-index',
    name: 'Selwin Full Index File - 14"',
    subtitle: '14 inch · Index dividers · Mix colors',
    category: 'Files & Folders',
    rating: 4.5,
    reviewCount: 678,
    currentPrice: 95,
    mrp: 140,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1696992812765-b7522af78a5f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmdWxsJTIwaW5kZXglMjBmaWxlJTIwZGl2aWRlciUyMHRhYnN8ZW58MXx8fHwxNzY5ODM5MjMyfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Large format file with full index dividers for organized document storage and quick access.',
    specifications: [
      { label: 'Type', value: 'Full Index file' },
      { label: 'Size', value: '14 inch' },
      { label: 'Features', value: 'Index dividers' },
      { label: 'Color', value: 'Mix colors' },
      { label: 'Brand', value: 'Selwin' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Large 14" format',
      'Full index dividers',
      'Easy document access',
      'Professional organization',
    ],
  },
  {
    id: 'file-l-folder',
    name: 'Ankita L Folder - A4',
    subtitle: 'Transparent plastic · A4 size · Document holder',
    category: 'Files & Folders',
    rating: 4.3,
    reviewCount: 543,
    currentPrice: 25,
    mrp: 40,
    discount: 38,
    images: ['https://images.unsplash.com/photo-1630734242356-a6f858790740?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxMJTIwZm9sZGVyJTIwdHJhbnNwYXJlbnQlMjBwbGFzdGljfGVufDF8fHx8MTc2OTgzOTIzMnww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Transparent L-shaped folder for document protection and easy viewing. A4 size compatible.',
    specifications: [
      { label: 'Type', value: 'L Folder' },
      { label: 'Size', value: 'A4' },
      { label: 'Material', value: 'Transparent plastic' },
      { label: 'Thickness', value: 'Medium gauge' },
      { label: 'Brand', value: 'Ankita' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Transparent for easy viewing',
      'L-shaped design',
      'A4 compatible',
      'Lightweight and portable',
    ],
  },

  // GEOMETRY & MEASURING
  {
    id: 'geometry-box-domes',
    name: 'Domes Geometry Box X1',
    subtitle: 'Complete set · Metal instruments · Student essential',
    category: 'Geometry Sets',
    rating: 4.5,
    reviewCount: 1876,
    currentPrice: 120,
    mrp: 180,
    discount: 33,
    images: ['https://images.unsplash.com/photo-1596495577886-d920f1fb7238?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnZW9tZXRyeSUyMGJveCUyMG1hdGglMjBpbnN0cnVtZW50c3xlbnwxfHx8fDE3MzgzNDk0Mzh8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Complete geometry box with all essential mathematical instruments. Perfect for students.',
    specifications: [
      { label: 'Model', value: 'X1' },
      { label: 'Material', value: 'Metal instruments' },
      { label: 'Contents', value: 'Compass, divider, protractor, rulers' },
      { label: 'Case', value: 'Durable plastic box' },
      { label: 'Brand', value: 'Domes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Complete instrument set',
      'Durable metal construction',
      'Compact storage case',
      'Student essential',
    ],
  },
  {
    id: 'scale-plastic-domes',
    name: 'Domes Plastic Scale - 12 inches',
    subtitle: '12 inches · Transparent · Metric & imperial',
    category: 'Geometry Sets',
    rating: 4.4,
    reviewCount: 1234,
    currentPrice: 15,
    mrp: 25,
    discount: 40,
    images: ['https://images.unsplash.com/photo-1685038408124-e20ecac92293?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwbGFzdGljJTIwcnVsZXIlMjBzY2FsZSUyMGluY2hlc3xlbnwxfHx8fDE3Njk4MzkyMjF8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Standard 12-inch plastic ruler with both metric and imperial measurements. Clear markings.',
    specifications: [
      { label: 'Material', value: 'Plastic' },
      { label: 'Length', value: '12 inches / 30 cm' },
      { label: 'Type', value: 'Transparent' },
      { label: 'Measurements', value: 'Metric & Imperial' },
      { label: 'Brand', value: 'Domes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '12 inch length',
      'Transparent plastic',
      'Clear markings',
      'Dual measurement system',
    ],
  },
  {
    id: 'scale-metal-12inch',
    name: 'Metal Scale - 12 inches',
    subtitle: 'Stainless steel · Precise markings · Durable',
    category: 'Geometry Sets',
    rating: 4.6,
    reviewCount: 987,
    currentPrice: 45,
    mrp: 70,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1685038408124-e20ecac92293?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZXRhbCUyMHJ1bGVyJTIwc2NhbGUlMjBtZWFzdXJpbmd8ZW58MXx8fHwxNzY5ODM5MjIxfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional-grade metal ruler with precise markings. Durable stainless steel construction.',
    specifications: [
      { label: 'Material', value: 'Metal / Stainless steel' },
      { label: 'Length', value: '12 inches / 30 cm' },
      { label: 'Type', value: 'Professional grade' },
      { label: 'Measurements', value: 'Precise etched markings' },
      { label: 'Brand', value: 'Generic' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Stainless steel construction',
      'Precise measurements',
      'Professional quality',
      'Long-lasting durability',
    ],
  },
  {
    id: 'scale-infinity-small',
    name: 'Infinity Small Scale - 4.8 inches',
    subtitle: 'Compact size · Portable · Student essential',
    category: 'Geometry Sets',
    rating: 4.2,
    reviewCount: 756,
    currentPrice: 8,
    mrp: 15,
    discount: 47,
    images: ['https://images.unsplash.com/photo-1685038408124-e20ecac92293?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwbGFzdGljJTIwcnVsZXIlMjBzY2FsZSUyMGluY2hlc3xlbnwxfHx8fDE3Njk4MzkyMjF8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Compact 4.8-inch scale perfect for pencil boxes and small measurements. Portable and convenient.',
    specifications: [
      { label: 'Material', value: 'Plastic' },
      { label: 'Length', value: '4.8 inches / 12 cm' },
      { label: 'Type', value: 'Compact' },
      { label: 'Features', value: 'Portable size' },
      { label: 'Brand', value: 'Infinity' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Compact 4.8" size',
      'Fits in pencil box',
      'Lightweight',
      'Perfect for students',
    ],
  },

  // GIFT SETS & ART SUPPLIES
  {
    id: 'gift-set-painting-kit',
    name: 'Domes Art & Craft Painting Gift Set',
    subtitle: 'Complete kit · Colors & brushes · Creative fun',
    category: 'Gift Sets',
    rating: 4.6,
    reviewCount: 876,
    currentPrice: 299,
    mrp: 450,
    discount: 34,
    images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWludGluZyUyMGtpdCUyMGFydCUyMHNldHxlbnwxfHx8fDE3MzgzNDk0Mzh8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Complete art gift set with painting supplies, colors, brushes, and accessories. Perfect gift for kids.',
    specifications: [
      { label: 'Type', value: 'Painting Kit gift set' },
      { label: 'Contents', value: 'Colors, brushes, palette, accessories' },
      { label: 'Age Group', value: '5+ years' },
      { label: 'Packaging', value: 'Gift box' },
      { label: 'Brand', value: 'Domes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Complete art supplies',
      'Perfect gift packaging',
      'Premium materials',
      'Ideal for creative kids',
    ],
  },
  {
    id: 'gift-set-general',
    name: 'Domes Stationery Gift Set',
    subtitle: 'Assorted items · Mix colors · Complete package',
    category: 'Gift Sets',
    rating: 4.5,
    reviewCount: 654,
    currentPrice: 249,
    mrp: 380,
    discount: 34,
    images: ['https://images.unsplash.com/photo-1513364776144-60967b0f800f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWludGluZyUyMGtpdCUyMGFydCUyMHNldHxlbnwxfHx8fDE3MzgzNDk0Mzh8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Complete stationery gift set with assorted items. Perfect for students and office use.',
    specifications: [
      { label: 'Type', value: 'Stationery gift set' },
      { label: 'Contents', value: 'Mix stationery items' },
      { label: 'Color', value: 'Mix colors' },
      { label: 'Packaging', value: 'Gift box' },
      { label: 'Brand', value: 'Domes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Complete stationery set',
      'Assorted useful items',
      'Gift packaging',
      'Great value',
    ],
  },
  {
    id: 'paint-brush-set-pointed',
    name: 'Magic Paint Brush Set - Pointed 0.7G',
    subtitle: '6 pieces · Pointed tip · Professional quality',
    category: 'Art Supplies',
    rating: 4.5,
    reviewCount: 543,
    currentPrice: 85,
    mrp: 130,
    discount: 35,
    images: ['https://images.unsplash.com/photo-1760270049613-4b670a965673?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWludCUyMGJydXNoZXMlMjBzZXQlMjBhcnR8ZW58MXx8fHwxNzY5ODM5MjE5fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional pointed paint brushes ideal for fine detail work. Set of 6 high-quality brushes.',
    specifications: [
      { label: 'Type', value: 'Pointed brush set' },
      { label: 'Size', value: '0.7G 6 pieces' },
      { label: 'Bristles', value: 'Synthetic/Natural blend' },
      { label: 'Use', value: 'Fine detail work' },
      { label: 'Brand', value: 'Magic' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '6 professional brushes',
      'Pointed tips for detail',
      'Quality bristles',
      'Versatile art tool',
    ],
  },
  {
    id: 'paint-brush-set-flat',
    name: 'Magic Paint Brush Set - Flat 0.7G',
    subtitle: '7 pieces · Flat tip · Multi-size set',
    category: 'Art Supplies',
    rating: 4.6,
    reviewCount: 456,
    currentPrice: 95,
    mrp: 145,
    discount: 34,
    images: ['https://images.unsplash.com/photo-1760270049613-4b670a965673?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwYWludCUyMGJydXNoZXMlMjBzZXQlMjBhcnR8ZW58MXx8fHwxNzY5ODM5MjE5fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Flat paint brush set with 7 different sizes. Perfect for broad strokes and coverage.',
    specifications: [
      { label: 'Type', value: 'Flat brush set' },
      { label: 'Size', value: '0.7G 7 pieces' },
      { label: 'Bristles', value: 'Premium quality' },
      { label: 'Use', value: 'Broad strokes & coverage' },
      { label: 'Brand', value: 'Magic' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '7 piece multi-size set',
      'Flat tips for coverage',
      'Professional quality',
      'Versatile painting',
    ],
  },
  {
    id: 'poster-color-domes',
    name: 'Domes Poster Color Set - Medium',
    subtitle: '6 colors · Medium bottles · Vibrant colors',
    category: 'Art Supplies',
    rating: 4.7,
    reviewCount: 1234,
    currentPrice: 145,
    mrp: 220,
    discount: 34,
    images: ['https://images.unsplash.com/photo-1706593095573-f3176b2677d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwb3N0ZXIlMjBwYWludCUyMGNvbG9ycyUyMHNldHxlbnwxfHx8fDE3Njk4MzkyMTl8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Vibrant poster colors in medium-sized bottles. Perfect for art projects and school work.',
    specifications: [
      { label: 'Type', value: 'Poster colors' },
      { label: 'Size', value: 'Medium bottles' },
      { label: 'Colors', value: 'Mix - 6 colors' },
      { label: 'Finish', value: 'Matte/Opaque' },
      { label: 'Brand', value: 'Domes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '6 vibrant colors',
      'Medium-sized bottles',
      'Non-toxic formula',
      'Perfect for projects',
    ],
  },

  // PENS & PENCILS
  {
    id: 'gel-pen-blue',
    name: 'Smooth-Flow Gel Pen – Blue Ink',
    subtitle: 'Comfort grip · Smudge-free writing',
    category: 'Pens',
    rating: 4.5,
    reviewCount: 2847,
    currentPrice: 149,
    mrp: 249,
    discount: 40,
    images: ['https://images.unsplash.com/photo-1757358678245-6151f66a699c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibHVlJTIwZ2VsJTIwcGVuJTIwd2hpdGUlMjBiYWNrZ3JvdW5kfGVufDF8fHx8MTc2OTEwNzAzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium gel pen featuring advanced ink technology. Ergonomic rubber grip ensures comfortable writing.',
    specifications: [
      { label: 'Material', value: 'Premium plastic body' },
      { label: 'Ink Type', value: 'Gel-based, quick-dry' },
      { label: 'Tip Size', value: '0.7mm' },
      { label: 'Grip Type', value: 'Rubber comfort grip' },
      { label: 'Refillable', value: 'Yes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Smooth gel ink',
      'Quick-dry formula',
      'Ergonomic grip',
      'Refillable cartridges',
    ],
    variants: {
      colors: [
        { id: 'blue', label: 'Blue' },
        { id: 'black', label: 'Black' },
        { id: 'red', label: 'Red' },
        { id: 'green', label: 'Green' },
      ],
      sizes: [
        { id: '0.5mm', label: '0.5mm' },
        { id: '0.7mm', label: '0.7mm' },
        { id: '1.0mm', label: '1.0mm' },
      ],
    },
  },
  {
    id: 'pen-klassy-goldex',
    name: 'Goldex Klassy Ball Pen - Blue',
    subtitle: 'Pack of 5 · Smooth writing · Blue ink',
    category: 'Pens',
    rating: 4.3,
    reviewCount: 1234,
    currentPrice: 35,
    mrp: 55,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1600531597946-f9b1d7b0f486?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWxscG9pbnQlMjBwZW4lMjBibHVlJTIwd3JpdGluZ3xlbnwxfHx8fDE3Njk4MzkyMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Economical ball pen with smooth writing performance. Pack of 5 pens for everyday use.',
    specifications: [
      { label: 'Type', value: 'Klassy ball pen' },
      { label: 'Ink Color', value: 'Blue' },
      { label: 'Pack', value: '5 pens' },
      { label: 'Tip', value: 'Medium ballpoint' },
      { label: 'Brand', value: 'Goldex' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Pack of 5 pens',
      'Smooth blue ink',
      'Economical choice',
      'Reliable writing',
    ],
  },
  {
    id: 'pen-ballpen-marlow',
    name: 'Marlow Ball Pen - Pack of 10',
    subtitle: 'Blue ink · Bulk pack · Value for money',
    category: 'Pens',
    rating: 4.2,
    reviewCount: 876,
    currentPrice: 55,
    mrp: 90,
    discount: 39,
    images: ['https://images.unsplash.com/photo-1600531597946-f9b1d7b0f486?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWxscG9pbnQlMjBwZW4lMjBibHVlJTIwd3JpdGluZ3xlbnwxfHx8fDE3Njk4MzkyMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Bulk pack of 10 ball pens with blue ink. Great value for offices and schools.',
    specifications: [
      { label: 'Type', value: 'Ball pen' },
      { label: 'Ink Color', value: 'Blue' },
      { label: 'Pack', value: '10 pens' },
      { label: 'Tip', value: 'Standard ballpoint' },
      { label: 'Brand', value: 'Marlow' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Pack of 10 pens',
      'Great value',
      'Blue ink',
      'Bulk purchase option',
    ],
  },
  {
    id: 'pen-pentonic-ballpen',
    name: 'Pentonic Ball Pen - Pack of 10',
    subtitle: 'Blue ink · Quality writing · Reliable',
    category: 'Pens',
    rating: 4.4,
    reviewCount: 1567,
    currentPrice: 75,
    mrp: 110,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1600531597946-f9b1d7b0f486?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWxscG9pbnQlMjBwZW4lMjBibHVlJTIwd3JpdGluZ3xlbnwxfHx8fDE3Njk4MzkyMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Quality ball pens from Pentonic. Pack of 10 for bulk use in offices and schools.',
    specifications: [
      { label: 'Type', value: 'Ball pen' },
      { label: 'Ink Color', value: 'Blue' },
      { label: 'Pack', value: '10 pens' },
      { label: 'Tip', value: 'Fine ballpoint' },
      { label: 'Brand', value: 'Pentonic' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Quality Pentonic brand',
      'Pack of 10',
      'Smooth blue ink',
      'Reliable performance',
    ],
  },
  {
    id: 'pen-pentonic-gelpen',
    name: 'Pentonic Gel Pen - Pack of 10',
    subtitle: 'Blue gel ink · Smooth flow · Pack of 10',
    category: 'Pens',
    rating: 4.5,
    reviewCount: 1876,
    currentPrice: 125,
    mrp: 180,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1757358678245-6151f66a699c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxibHVlJTIwZ2VsJTIwcGVuJTIwd2hpdGUlMjBiYWNrZ3JvdW5kfGVufDF8fHx8MTc2OTEwNzAzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium gel pens with smooth flowing blue ink. Pack of 10 for office and school use.',
    specifications: [
      { label: 'Type', value: 'Gel pen' },
      { label: 'Ink Color', value: 'Blue' },
      { label: 'Pack', value: '10 pens' },
      { label: 'Tip Size', value: '0.7mm' },
      { label: 'Brand', value: 'Pentonic' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Smooth gel ink',
      'Pack of 10 pens',
      'Premium quality',
      'Great for bulk use',
    ],
  },
  {
    id: 'pen-use-throw-topfom',
    name: 'Topfom Use & Throw Ball Pen - 50 Pack',
    subtitle: 'Bulk pack · Blue ink · Disposable pens',
    category: 'Pens',
    rating: 4.1,
    reviewCount: 2345,
    currentPrice: 195,
    mrp: 280,
    discount: 30,
    images: ['https://images.unsplash.com/photo-1600531597946-f9b1d7b0f486?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWxscG9pbnQlMjBwZW4lMjBibHVlJTIwd3JpdGluZ3xlbnwxfHx8fDE3Njk4MzkyMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Bulk pack of 50 disposable use-and-throw pens. Perfect for events, offices, and bulk distribution.',
    specifications: [
      { label: 'Type', value: 'Ball pen - Use & Throw' },
      { label: 'Ink Color', value: 'Blue' },
      { label: 'Pack', value: '50 pens' },
      { label: 'Tip', value: 'Standard ballpoint' },
      { label: 'Brand', value: 'Topfom' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Bulk pack of 50',
      'Disposable design',
      'Great for events',
      'Maximum value',
    ],
  },
  {
    id: 'pen-ball-balaji',
    name: 'Balaji Ball Pen - Pack of 20',
    subtitle: 'Blue ink · Mid-size pack · Reliable',
    category: 'Pens',
    rating: 4.3,
    reviewCount: 765,
    currentPrice: 95,
    mrp: 140,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1600531597946-f9b1d7b0f486?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWxscG9pbnQlMjBwZW4lMjBibHVlJTIwd3JpdGluZ3xlbnwxfHx8fDE3Njk4MzkyMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Quality ball pens in pack of 20. Perfect for medium-scale bulk requirements.',
    specifications: [
      { label: 'Type', value: 'Ball pen' },
      { label: 'Ink Color', value: 'Blue' },
      { label: 'Pack', value: '20 pens' },
      { label: 'Tip', value: 'Medium ballpoint' },
      { label: 'Brand', value: 'Balaji' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Pack of 20 pens',
      'Mid-size bulk option',
      'Reliable writing',
      'Value pricing',
    ],
  },
  {
    id: 'pen-hal-apagra',
    name: 'Apagra Hal Pen - Pack of 10',
    subtitle: 'Special design · Quality ink · Multi-purpose',
    category: 'Pens',
    rating: 4.2,
    reviewCount: 543,
    currentPrice: 85,
    mrp: 125,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1600531597946-f9b1d7b0f486?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiYWxscG9pbnQlMjBwZW4lMjBibHVlJTIwd3JpdGluZ3xlbnwxfHx8fDE3Njk4MzkyMzJ8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Special design Hal pen from Apagra. Pack of 10 for various writing needs.',
    specifications: [
      { label: 'Type', value: 'Hal pen' },
      { label: 'Design', value: 'Special' },
      { label: 'Pack', value: '10 pens' },
      { label: 'Features', value: 'Multi-purpose' },
      { label: 'Brand', value: 'Apagra' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Special Hal design',
      'Pack of 10',
      'Quality construction',
      'Versatile use',
    ],
  },
  {
    id: 'glitter-pen',
    name: 'Sparkle Glitter Pen',
    subtitle: 'Metallic colors · Smooth flow · Creative writing',
    category: 'Pens',
    rating: 4.3,
    reviewCount: 654,
    currentPrice: 35,
    mrp: 55,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1565967511849-76a60a516170?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnbGl0dGVyJTIwcGVuJTIwY29sb3JmdWx8ZW58MXx8fHwxNzM4MzQ5NDM4fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Add sparkle to your writing with these glitter pens. Perfect for greeting cards and creative projects.',
    specifications: [
      { label: 'Type', value: 'Glitter gel pen' },
      { label: 'Tip Size', value: '1.0mm' },
      { label: 'Ink Type', value: 'Gel with glitter' },
      { label: 'Features', value: 'Metallic shimmer' },
      { label: 'Brand', value: 'Generic' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Sparkly metallic colors',
      'Smooth gel ink',
      'Perfect for crafts',
      'Creative writing',
    ],
    variants: {
      colors: [
        { id: 'gold', label: 'Gold' },
        { id: 'silver', label: 'Silver' },
        { id: 'pink', label: 'Pink' },
        { id: 'blue', label: 'Blue' },
        { id: 'purple', label: 'Purple' },
      ],
    },
  },
  {
    id: 'pencil-zoom-domes',
    name: 'Domes Zoom Pencil - Pack of 10',
    subtitle: 'HB grade · Quality wood · Sharp writing',
    category: 'Pencils',
    rating: 4.4,
    reviewCount: 1876,
    currentPrice: 45,
    mrp: 70,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1593435221502-c5d7bfc26cab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZW5jaWwlMjBIQiUyMHdvb2RlbiUyMHN0dWRlbnR8ZW58MXx8fHwxNzY5ODM5MjIwfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Quality wooden pencils with smooth graphite. Pack of 10 for school and office use.',
    specifications: [
      { label: 'Type', value: 'Zoom pencil' },
      { label: 'Grade', value: 'HB' },
      { label: 'Pack', value: '10 pencils' },
      { label: 'Material', value: 'Quality wood' },
      { label: 'Brand', value: 'Domes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'HB grade graphite',
      'Pack of 10 pencils',
      'Smooth writing',
      'Quality construction',
    ],
  },
  {
    id: 'pencil-hb-nataraj',
    name: 'Nataraj HB Pencil - Pack of 10',
    subtitle: 'Premium quality · HB grade · Trusted brand',
    category: 'Pencils',
    rating: 4.7,
    reviewCount: 3421,
    currentPrice: 55,
    mrp: 80,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1593435221502-c5d7bfc26cab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZW5jaWwlMjBIQiUyMHdvb2RlbiUyMHN0dWRlbnR8ZW58MXx8fHwxNzY5ODM5MjIwfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium Nataraj HB pencils, trusted by students and professionals. Pack of 10 quality pencils.',
    specifications: [
      { label: 'Type', value: 'HB pencil' },
      { label: 'Grade', value: 'HB' },
      { label: 'Pack', value: '10 pencils' },
      { label: 'Material', value: 'Premium wood & graphite' },
      { label: 'Brand', value: 'Nataraj' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Premium Nataraj quality',
      'HB grade standard',
      'Smooth graphite',
      'Trusted brand',
    ],
  },
  {
    id: 'pencil-with-lead',
    name: 'Classmate Mechanical Pencil with Lead',
    subtitle: '0.5mm lead · 1+1 pack · Refillable',
    category: 'Pencils',
    rating: 4.6,
    reviewCount: 1234,
    currentPrice: 35,
    mrp: 55,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1730201623502-11031bb4de85?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtZWNoYW5pY2FsJTIwcGVuY2lsJTIwbGVhZCUyMHJlZmlsbHxlbnwxfHx8fDE3Njk4MzkyMjB8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Mechanical pencil with 0.5mm lead. Comes with bonus refill pack (1+1). Perfect for technical drawing.',
    specifications: [
      { label: 'Type', value: 'Mechanical pencil with lead' },
      { label: 'Lead Size', value: '0.5mm' },
      { label: 'Pack', value: '1+1 (Pencil + Lead refill)' },
      { label: 'Features', value: 'Refillable' },
      { label: 'Brand', value: 'Classmate' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '0.5mm precision lead',
      'Includes refill pack',
      'Mechanical convenience',
      'Technical drawing ready',
    ],
  },

  // HIGHLIGHTERS & MARKERS
  {
    id: 'highlighter-luxor',
    name: 'Luxor Highlighter Pen - Pack of 5',
    subtitle: 'Bright colors · Chisel tip · Mix colors',
    category: 'Highlighters',
    rating: 4.6,
    reviewCount: 1287,
    currentPrice: 125,
    mrp: 180,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1590859808308-3d2d9c515b1a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoaWdobGlnaHRlciUyMHBlbiUyMGNvbG9yZnVsfGVufDF8fHx8MTczODM0OTQzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Vibrant highlighter pens with chisel tips. Water-based ink won\'t bleed through paper. Pack of 5.',
    specifications: [
      { label: 'Type', value: 'Highlighter pen' },
      { label: 'Tip Type', value: 'Chisel tip' },
      { label: 'Pack', value: '5 highlighters' },
      { label: 'Colors', value: 'Mix colors' },
      { label: 'Brand', value: 'Luxor' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Pack of 5 colors',
      'Chisel tip versatility',
      'Water-based ink',
      'No bleed-through',
    ],
  },
  {
    id: 'permanent-marker-luxor-ohp',
    name: 'Luxor Permanent Marker OHP - Pack of 5',
    subtitle: 'Pointed tip · Black ink · Permanent',
    category: 'Markers',
    rating: 4.5,
    reviewCount: 876,
    currentPrice: 155,
    mrp: 225,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1554284191-096482f50049?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZXJtYW5lbnQlMjBtYXJrZXIlMjBwZW4lMjBibGFja3xlbnwxfHx8fDE3Njk4MzkyMTl8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional permanent marker with pointed tip for OHP sheets and various surfaces. Pack of 5.',
    specifications: [
      { label: 'Type', value: 'Permanent Marker - Pointed - OHP' },
      { label: 'Tip Type', value: 'Pointed' },
      { label: 'Pack', value: '5 markers' },
      { label: 'Color', value: 'Black' },
      { label: 'Brand', value: 'Luxor' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Permanent ink',
      'Pointed tip precision',
      'OHP compatible',
      'Pack of 5',
    ],
  },
  {
    id: 'permanent-marker-addgel',
    name: 'Add Gel Permanent Marker Pen',
    subtitle: 'Fine tip · Black ink · Multi-surface',
    category: 'Markers',
    rating: 4.4,
    reviewCount: 654,
    currentPrice: 35,
    mrp: 55,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1554284191-096482f50049?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwZXJtYW5lbnQlMjBtYXJrZXIlMjBwZW4lMjBibGFja3xlbnwxfHx8fDE3Njk4MzkyMTl8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Permanent marker with fine tip for precise marking on multiple surfaces. Black ink.',
    specifications: [
      { label: 'Type', value: 'Permanent Marker pen' },
      { label: 'Tip Type', value: 'Fine point' },
      { label: 'Pack', value: '1 marker' },
      { label: 'Color', value: 'Black' },
      { label: 'Brand', value: 'Add Gel' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Fine tip precision',
      'Permanent black ink',
      'Multi-surface marking',
      'Professional quality',
    ],
  },
  {
    id: 'whiteboard-marker-addgel',
    name: 'Add Gel Whiteboard Marker',
    subtitle: 'Black ink · Erasable · Dry-erase',
    category: 'Markers',
    rating: 4.5,
    reviewCount: 987,
    currentPrice: 45,
    mrp: 70,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1662304514018-8fd19cd4fc1b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZWJvYXJkJTIwbWFya2VyJTIwYmxhY2t8ZW58MXx8fHwxNzY5ODM5MjIyfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Dry-erase whiteboard marker with black ink. Easily erasable and perfect for presentations.',
    specifications: [
      { label: 'Type', value: 'Whiteboard marker' },
      { label: 'Tip Type', value: 'Chisel/Bullet' },
      { label: 'Pack', value: '1 marker' },
      { label: 'Color', value: 'Black' },
      { label: 'Brand', value: 'Add Gel' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Dry-erase formula',
      'Easy to wipe clean',
      'Bold black ink',
      'Presentation ready',
    ],
  },

  // OFFICE ACCESSORIES
  {
    id: 'stapler-domes',
    name: 'Domes Office Stapler',
    subtitle: 'Standard size · Metal body · Reliable',
    category: 'Office Accessories',
    rating: 4.4,
    reviewCount: 765,
    currentPrice: 95,
    mrp: 145,
    discount: 34,
    images: ['https://images.unsplash.com/photo-1765407418531-06a22ef8d2ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvZmZpY2UlMjBzdGFwbGVyJTIwbWV0YWx8ZW58MXx8fHwxNzY5ODM5MjE5fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Durable office stapler with metal body. Reliable performance for everyday document binding.',
    specifications: [
      { label: 'Type', value: 'Office stapler' },
      { label: 'Material', value: 'Metal body' },
      { label: 'Capacity', value: 'Up to 20 sheets' },
      { label: 'Staple Size', value: 'Standard (No. 10)' },
      { label: 'Brand', value: 'Domes' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Metal construction',
      'Staples up to 20 sheets',
      'Standard staple size',
      'Reliable performance',
    ],
  },
  {
    id: 'stapler-kangaro',
    name: 'Kangaro Standard Stapler',
    subtitle: 'Professional quality · Ergonomic · Durable',
    category: 'Office Accessories',
    rating: 4.6,
    reviewCount: 1234,
    currentPrice: 125,
    mrp: 185,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1765407418531-06a22ef8d2ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvZmZpY2UlMjBzdGFwbGVyJTIwbWV0YWx8ZW58MXx8fHwxNzY5ODM5MjE5fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional Kangaro stapler with ergonomic design. High-quality construction for heavy use.',
    specifications: [
      { label: 'Type', value: 'Professional stapler' },
      { label: 'Material', value: 'High-grade metal' },
      { label: 'Capacity', value: 'Up to 25 sheets' },
      { label: 'Staple Size', value: 'Standard' },
      { label: 'Brand', value: 'Kangaro' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Premium Kangaro quality',
      'Ergonomic design',
      'Up to 25 sheets',
      'Heavy-duty use',
    ],
  },
  {
    id: 'stapler-kangaro-hd10d',
    name: 'Kangaro HD-10D Heavy Duty Stapler',
    subtitle: 'Heavy duty · Professional · High capacity',
    category: 'Office Accessories',
    rating: 4.7,
    reviewCount: 987,
    currentPrice: 185,
    mrp: 270,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1765407418531-06a22ef8d2ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvZmZpY2UlMjBzdGFwbGVyJTIwbWV0YWx8ZW58MXx8fHwxNzY5ODM5MjE5fDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Heavy-duty Kangaro HD-10D stapler for professional office use. High capacity and durability.',
    specifications: [
      { label: 'Model', value: 'HD - 10 D' },
      { label: 'Type', value: 'Heavy duty stapler' },
      { label: 'Material', value: 'Industrial-grade metal' },
      { label: 'Capacity', value: 'Up to 50 sheets' },
      { label: 'Brand', value: 'Kangaro' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Heavy-duty capacity',
      'Staples up to 50 sheets',
      'Industrial strength',
      'Professional grade',
    ],
  },
  {
    id: 'punching-machine-kangaro',
    name: 'Kangaro Punching Machine No 2/80',
    subtitle: '8 cm punch · 2-hole · Heavy duty',
    category: 'Office Accessories',
    rating: 4.5,
    reviewCount: 654,
    currentPrice: 295,
    mrp: 425,
    discount: 31,
    images: ['https://images.unsplash.com/photo-1521800641212-77d98bb90d21?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxvZmZpY2UlMjBwdW5jaGluZyUyMG1hY2hpbmUlMjBob2xlJTIwcHVuY2h8ZW58MXx8fHwxNzY5ODM5MjMwfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Professional 2-hole punching machine with 8cm capacity. Ideal for office document filing.',
    specifications: [
      { label: 'Model', value: 'No 2/80' },
      { label: 'Type', value: 'Punching machine' },
      { label: 'Capacity', value: '8 cm punch depth' },
      { label: 'Holes', value: '2-hole' },
      { label: 'Brand', value: 'Kangaro' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Professional 2-hole punch',
      '8cm capacity',
      'Heavy-duty construction',
      'Precision punching',
    ],
  },
  {
    id: 'pins-pushpins',
    name: 'Push Pins / Thumb Tacks',
    subtitle: 'Colorful pins · Multi-purpose · Notice board',
    category: 'Office Accessories',
    rating: 4.3,
    reviewCount: 543,
    currentPrice: 35,
    mrp: 55,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1711610378090-779a7881a789?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwdXNoJTIwcGlucyUyMHRodW1idGFja3MlMjBjb2xvcmZ1bHxlbnwxfHx8fDE3Njk4MzkyMzN8MA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Colorful push pins for notice boards and bulletin displays. Pack of assorted colors.',
    specifications: [
      { label: 'Type', value: 'Push pins / Thumb tacks' },
      { label: 'Material', value: 'Metal pin with plastic head' },
      { label: 'Colors', value: 'Assorted' },
      { label: 'Pack', value: '50 pieces' },
      { label: 'Use', value: 'Notice boards, displays' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Colorful assorted pins',
      'Pack of 50 pieces',
      'Notice board essential',
      'Durable construction',
    ],
  },

  // TAPES & ADHESIVE ACCESSORIES
  {
    id: 'masking-tape',
    name: 'Masking Tape - 1 inch',
    subtitle: 'Beige color · Easy peel · Painting aid',
    category: 'Tapes & Adhesives',
    rating: 4.4,
    reviewCount: 567,
    currentPrice: 45,
    mrp: 70,
    discount: 36,
    images: ['https://images.unsplash.com/photo-1582092026324-5b840e473dce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY290Y2glMjB0YXBlJTIwM00lMjBkaXNwZW5zZXJ8ZW58MXx8fHwxNzY5ODM5MjIyfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Painter\'s masking tape for clean edges and easy removal. 1-inch width for various applications.',
    specifications: [
      { label: 'Type', value: 'Masking tape' },
      { label: 'Width', value: '1 inch (25mm)' },
      { label: 'Length', value: '15 meters' },
      { label: 'Color', value: 'Beige/Tan' },
      { label: 'Use', value: 'Painting, masking' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      '1-inch width',
      'Easy peel & removal',
      'No residue',
      'Painting essential',
    ],
  },
  {
    id: 'scotch-tape-3m',
    name: '3M Scotch Magic Tape',
    subtitle: 'Transparent · Invisible finish · Multi-purpose',
    category: 'Tapes & Adhesives',
    rating: 4.7,
    reviewCount: 1876,
    currentPrice: 85,
    mrp: 125,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1582092026324-5b840e473dce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY290Y2glMjB0YXBlJTIwM00lMjBkaXNwZW5zZXJ8ZW58MXx8fHwxNzY5ODM5MjIyfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Premium 3M Scotch Magic Tape with invisible finish. Perfect for gift wrapping and document repair.',
    specifications: [
      { label: 'Type', value: 'Magic Tape' },
      { label: 'Width', value: '19mm' },
      { label: 'Length', value: '33 meters' },
      { label: 'Finish', value: 'Matte transparent' },
      { label: 'Brand', value: '3M' },
      { label: 'Country of Origin', value: 'USA' },
    ],
    highlights: [
      'Premium 3M quality',
      'Invisible matte finish',
      'Write on surface',
      'Multi-purpose use',
    ],
  },
  {
    id: 'packing-tape-wonder',
    name: 'Wonder Packing Tape - 2 inches Brown',
    subtitle: 'Heavy duty · Brown · Strong adhesion',
    category: 'Tapes & Adhesives',
    rating: 4.5,
    reviewCount: 987,
    currentPrice: 65,
    mrp: 95,
    discount: 32,
    images: ['https://images.unsplash.com/photo-1582092026324-5b840e473dce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY290Y2glMjB0YXBlJTIwM00lMjBkaXNwZW5zZXJ8ZW58MXx8fHwxNzY5ODM5MjIyfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Heavy-duty brown packing tape for sealing boxes and packages. Strong adhesive for secure shipping.',
    specifications: [
      { label: 'Type', value: 'Packing tape' },
      { label: 'Width', value: '2 inches (50mm)' },
      { label: 'Length', value: '40 meters' },
      { label: 'Color', value: 'Brown' },
      { label: 'Brand', value: 'Wonder' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Heavy-duty adhesion',
      '2-inch width',
      'Perfect for packing',
      'Strong and durable',
    ],
  },
  {
    id: 'cello-tags-wonder',
    name: 'Wonder Transparent Cello Tags',
    subtitle: 'Roll format · Transparent · Gift wrapping',
    category: 'Tapes & Adhesives',
    rating: 4.3,
    reviewCount: 432,
    currentPrice: 55,
    mrp: 85,
    discount: 35,
    images: ['https://images.unsplash.com/photo-1582092026324-5b840e473dce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzY290Y2glMjB0YXBlJTIwM00lMjBkaXNwZW5zZXJ8ZW58MXx8fHwxNzY5ODM5MjIyfDA&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Transparent cellophane tape in roll format. Perfect for gift wrapping and crafts.',
    specifications: [
      { label: 'Type', value: 'Cello tags / Cellophane tape' },
      { label: 'Format', value: 'Roll' },
      { label: 'Finish', value: 'Transparent' },
      { label: 'Use', value: 'Gift wrapping, crafts' },
      { label: 'Brand', value: 'Wonder' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Clear transparent finish',
      'Gift wrapping essential',
      'Easy to use roll',
      'Versatile application',
    ],
  },

  // HOUSEHOLD ITEMS (Non-stationery but in list)
  {
    id: 'cloth-duster',
    name: 'Cotton Cloth Duster - Pack of 12',
    subtitle: 'Small size · Mix colors · Cleaning cloth',
    category: 'Cleaning Supplies',
    rating: 4.2,
    reviewCount: 543,
    currentPrice: 85,
    mrp: 130,
    discount: 35,
    images: ['https://images.unsplash.com/photo-1563453392212-326f5e854473?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjbG90aCUyMGR1c3RlciUyMGNsZWFuaW5nfGVufDF8fHx8MTczODM0OTQzOHww&ixlib=rb-4.1.0&q=80&w=1080'],
    description: 'Soft cotton dusting cloths for cleaning surfaces. Pack of 12 in assorted colors.',
    specifications: [
      { label: 'Type', value: 'Cloth duster' },
      { label: 'Size', value: 'Small' },
      { label: 'Material', value: 'Cotton' },
      { label: 'Colors', value: 'Mix colors' },
      { label: 'Pack', value: '12 pieces' },
      { label: 'Country of Origin', value: 'India' },
    ],
    highlights: [
      'Pack of 12 cloths',
      'Soft cotton material',
      'Multi-purpose cleaning',
      'Reusable',
    ],
  },
];
